version: '3'
services:
  bggapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: bggapi:latest
    ports:
      - "8080:8080"
    volumes:
      - ./bggapi:/app/bggapi
