apiVersion: v1
kind: Service
metadata:
  name: bggapi-service
  namespace: default  # Specify the namespace here
spec:
  selector:
    app: bggapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
