apiVersion: v1
kind: Service
metadata:
  name: bggapi-service
  namespace: default
spec:
  selector:
    app: bggapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: <static-ip>

